export const PATHS = {
  home: '/',
  shop: '/shop',
  vehicleDetails: '/vehicles/:id',
  categories: '/categories',
  brands: '/brands',
  about: '/about',
  contact: '/contact',
  faq: '/faq',
  privacy: '/privacy',
  terms: '/terms',
  signIn: '/sign-in',
  signUp: '/sign-up',
  cart: '/cart',
  wishlist: '/wishlist',
  checkout: '/checkout',
  dashboard: '/dashboard',
  admin: '/admin',
}
