import { Breadcrumbs } from '@/components/ui/States'

const SECTIONS = [
  { title: 'Information We Collect', body: 'We collect information you provide directly (name, email, phone, delivery address, payment details) and information generated by your use of the platform (browsing history, saved vehicles, order history).' },
  { title: 'How We Use Your Information', body: 'Your information is used to process orders, personalize your experience, communicate about your account, and improve our services. We do not sell your personal data to third parties.' },
  { title: 'Payment Information', body: 'Payment processing is handled by our payment partners (Stripe, M-Pesa). alhusnain Motors does not store your full card or mobile money credentials on our servers.' },
  { title: 'Cookies', body: 'We use cookies to keep you signed in, remember your preferences, and understand how the platform is used so we can improve it.' },
  { title: 'Your Rights', body: 'You can access, correct, or request deletion of your personal data at any time from your account settings, or by contacting our support team.' },
  { title: 'Contact Us', body: 'Questions about this policy can be directed to privacy@alhusnainmotors.co.ke.' },
]

export default function Privacy() {
  return (
    <div className="pt-28 pb-24">
      <div className="mx-auto max-w-3xl px-6 lg:px-10">
        <Breadcrumbs items={[{ label: 'Home', to: '/' }, { label: 'Privacy Policy' }]} />
        <h1 className="font-display text-4xl lg:text-5xl uppercase text-bone mt-4 mb-2">Privacy Policy</h1>
        <p className="text-silver-dim text-sm mb-10">Last updated August 2026</p>

        <div className="flex flex-col gap-10">
          {SECTIONS.map((s) => (
            <div key={s.title}>
              <h2 className="font-display uppercase text-bone text-lg mb-2">{s.title}</h2>
              <p className="text-silver text-sm leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
